### PR TITLE
Hair additions

### PR DESCRIPTION
**Pull request by vloedlijn**
9 new hairstyles plus 1 iteration of the afro2 hairstyle already in-game.

### CODE REVIEW

**Comment by dumbmatter** [comment]
Thanks again for the PR!

I think the black background of the hair looks weird currently, for example:

image

Even with black hair it looks a bit strange.

And overall (applying to #24 too) I think the braids somehow look too detailed/realistic compared to the more cartoony look of the other facial features. Do you think there is some way to improve that?

**Comment by vloedlijn** [comment]
I changed the background of the hair to make it match the hair color. For the braids I tried making the stroke size bigger from 1 px to 2 px. And then to 4 px. The first image are the braids with a 2 px stroke, the second picture are the braids with a 4 px stroke, and the third picture has a 4 px stroke but with black hair instead of blonde.
Screenshot 2022-05-21 at 20-43-29 faces js editor
Screenshot 2022-05-21 at 20-47-52 faces js editor
Screenshot 2022-05-21 at 20-53-54 faces js editor
With how I made the initial designs, the stroke color wasn't black like it is in the first two pictures because the opacity lend itself well to any kind of hair color. In these new designs, to make them look more cartoony to match with the facial features, I had to give it a black stroke since the facial features in the game have #000000 borders.

**Comment by vloedlijn** [comment]
I guess there's also something like this, it's a quick mock up but essentially just hand drawn dreads. I personally think it looks a little messy and plain but it's another option. Hopefully we can pin a solution down!
Screenshot 2022-05-22 at 05-10-41 faces js editor

**Comment by dumbmatter** [comment]
I think it still just doesn't look good enough, either way. Sorry for not having more constructive feedback. I really don't know anything about graphics! @TravisJB89 what do you think?

**Comment by vloedlijn** [comment]
I'll keep working but understand if they just don't work for the game! Will get back soon with different designs.

**Pull request closed without merging**
